-- 011: SEED 324 đối tác thật từ sheet DM Đối tác
-- Idempotent.

DELETE FROM public.contractors WHERE code ~ '^(CT|CN|CQ|NH)[0-9]';
INSERT INTO public.contractors (code, name, type, category, transaction_count, rating, is_active) VALUES
  ('NH001','Ngân Hàng TMCP Tiên Phong','ncc','Ngân hàng',132,0,true),
  ('CN002','Huỳnh Thị Trúc Diễm','ncc','Cá nhân',76,0,true),
  ('CN003','Lại Nguyễn Lan Phương','ncc','Cá nhân',70,0,true),
  ('CN004','Phùng Nguyên Khôi','ncc','Cá nhân',68,0,true),
  ('CN005','Lê Thị Cẩm Giang','ncc','Cá nhân',61,0,true),
  ('CN006','Bùi Nhựt Duy','ncc','Cá nhân',57,0,true),
  ('CTY007','Công ty Cổ phần Xây dựng và Lắp máy Trung Nam','ncc','Công ty',52,0,true),
  ('CN008','Nguyễn Duy Hưng','ncc','Cá nhân',52,0,true),
  ('CN009','Trần Ngọc Hoàng','ncc','Cá nhân',52,0,true),
  ('CN010','Phan Tấn Phát','ncc','Cá nhân',44,0,true),
  ('CN011','Huỳnh Giáp Nhân','ncc','Cá nhân',41,0,true),
  ('CN012','Nguyễn Bích Như Quỳnh','ncc','Cá nhân',39,0,true),
  ('CN013','Phạm Thành Lộc','ncc','Cá nhân',38,0,true),
  ('CN014','Phạm Thanh Vy','ncc','Cá nhân',31,0,true),
  ('CN015','Nguyễn Thanh Hân-HCNS TNEC','ncc','Cá nhân (nội bộ)',26,0,true),
  ('CQ016','Bảo Hiểm Xã Hội huyện Di Linh','ncc','Cơ quan NN',25,0,true),
  ('CTY017','Công ty Cổ phần Dịch vụ và Kỹ thuật SMC','ncc','Công ty',23,0,true),
  ('CN018','Phạm Tánh - BĐH XLNT Châu Thành- Tây Ninh -Giai Đoạn 2','ncc','Cá nhân (nội bộ)',22,0,true),
  ('CN019','Lại Quý Dương','ncc','Cá nhân',22,0,true),
  ('CN020','Phan Thị Ái Loan','ncc','Cá nhân',20,0,true),
  ('CTY021','Công ty cổ phần An Cư Đức Phú','ncc','Công ty',18,0,true),
  ('CTY022','Công ty Cổ Phần Đầu tư Xây dựng Trung Nam','ncc','Công ty',17,0,true),
  ('CN023','Trần Thanh Tam','ncc','Cá nhân',17,0,true),
  ('CTY024','Công Ty TNHH Thương Mại Kỹ Thuật Xây Dựng Toàn Thắng','ncc','Công ty',15,0,true),
  ('CTY025','CÔNG TY TNHH THƯƠNG MẠI XUẤT NHẬP KHẨU HÀ KHÁNH','ncc','Công ty',15,0,true),
  ('CN026','Nguyễn Duy Khanh','ncc','Cá nhân',15,0,true),
  ('CN027','Đỗ Duy Khương- BĐH Nhà máy Điện mặt trời Trà Vinh - Giai Đoạn 2','ncc','Cá nhân (nội bộ)',13,0,true),
  ('CN028','Nguyễn Anh Quốc','ncc','Cá nhân',13,0,true),
  ('CTY029','Công Ty TNHH Sản Xuất Xây Dựng - Thương Mại Và Dịch Vụ Huỳnh Anh','ncc','Công ty',12,0,true),
  ('CN030','Đinh Kim Ngân','ncc','Cá nhân',12,0,true),
  ('CN031','Trần Thùy Dương','ncc','Cá nhân',12,0,true),
  ('CTY032','Công ty Cổ phần Di chuyển Xanh và Thông minh GSM','ncc','Công ty',12,0,true),
  ('CTY033','Công ty TNHH Thương mại Văn phòng phẩm Minh Khôi','ncc','Công ty',11,0,true),
  ('CN034','Chu Đình Tưởng','ncc','Cá nhân',11,0,true),
  ('CTY035','Công ty TNHH Thu Phí Tự động VETC','ncc','Công ty',11,0,true),
  ('CTY036','Công ty TNHH Bảo Hộ Lao Động Thành Phong','ncc','Công ty',10,0,true),
  ('CN037','Đặng Đình Quyền','ncc','Cá nhân',10,0,true),
  ('CN038','VƯƠNG QUÝ NHƯ','ncc','Cá nhân',10,0,true),
  ('CTY039','Công ty TNHH Xuân Sơn Hải Dương','ncc','Công ty',9,0,true),
  ('CTY040','Công ty Cổ phần Thiết bị Khoa học Công nghệ Tường Anh','ncc','Công ty',9,0,true),
  ('CTY041','Công ty Cổ phần Hai Bốn Bảy','ncc','Công ty',9,0,true),
  ('CN042','Hoàng Công Diệm','ncc','Cá nhân',9,0,true),
  ('CTY043','CÔNG TY TNHH XÂY DỰNG VÀ THƯƠNG MẠI SONG PHÚ','ncc','Công ty',8,0,true),
  ('CTY044','Công ty TNHH Giải Pháp Môi Trường Đại Nam','ncc','Công ty',8,0,true),
  ('CTY045','Công ty TNHH Thương mại và Dịch vụ CNS','ncc','Công ty',8,0,true),
  ('CN046','Nguyễn Minh Thảo-Phòng an toàn lao động','ncc','Cá nhân (nội bộ)',8,0,true),
  ('CTY047','Công ty TNHH Xây Dựng và Thương Mại Yên Phúc','ncc','Công ty',7,0,true),
  ('CN048','Nguyễn Trương Thùy Quyên','ncc','Cá nhân',7,0,true),
  ('CN049','Hồ Hoàng Cường-BĐH cống âu thuyền Vàm Lẽo','ncc','Cá nhân (nội bộ)',7,0,true),
  ('CN050','NGUYỄN HOÀNG VŨ','ncc','Cá nhân',7,0,true),
  ('CTY051','CÔNG TY TNHH MTV QUẢNG CÁO VĨNH TƯỜNG','ncc','Công ty',7,0,true),
  ('CTY052','Công ty TNHH Mỹ thuật Ứng dụng Trường Khánh','ncc','Công ty',6,0,true),
  ('CN053','LA THỊ PHƯƠNG HẰNG','ncc','Cá nhân',6,0,true),
  ('CN054','TRẦN THỊ DIỄM TRINH','ncc','Cá nhân',6,0,true),
  ('CTY055','Công Ty TNHH Phát Triển Tiến Thanh','ncc','Công ty',6,0,true),
  ('CTY056','Công Ty Cổ Phần Quản Lý Tòa Nhà The Useful','ncc','Công ty',6,0,true),
  ('CQ057','Ban Quản lý dự án đầu tư xây dựng tỉnh Tây Ninh','ncc','Cơ quan NN',6,0,true),
  ('CTY058','CÔNG TY TNHH MTV TRƯƠNG GIA LỘC','ncc','Công ty',5,0,true),
  ('CTY059','Công ty TNHH XD Minh Khang','ncc','Công ty',5,0,true),
  ('CTY060','Công ty Cổ phần Bán lẻ Kỹ thuật số FPT','ncc','Công ty',5,0,true),
  ('CTY061','CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ ICT SÀI GÒN','ncc','Công ty',5,0,true),
  ('CTY062','Công ty CP Sản Xuất và Đầu Tư Nội Thất Nam Việt','ncc','Công ty',5,0,true),
  ('CN063','TRẦN NGHIỆP QUANG','ncc','Cá nhân',5,0,true),
  ('CN064','Nguyễn Xuân Thanh - BĐH dự án XL01 Rạch Xuyên Tâm','ncc','Cá nhân (nội bộ)',5,0,true),
  ('CTY065','CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ NGHIỆP PHÁT ĐẠT','ncc','Công ty',5,0,true),
  ('CTY066','CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI VÀ DỊCH VỤ LÊ NGUYÊN','ncc','Công ty',5,0,true),
  ('CN067','Bùi Duy Tự','ncc','Cá nhân',5,0,true),
  ('CN068','Lê Sỹ Hòa - BĐH gói thầu KCN Cà Ná - GĐ1','ncc','Cá nhân (nội bộ)',5,0,true),
  ('CTY069','CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ QUẢNG CÁO HUỲNH GIA HÂN','ncc','Công ty',5,0,true),
  ('CN070','Trương Thành Phương- tài xế xe TNEC NEW','ncc','Cá nhân (nội bộ)',5,0,true),
  ('CN071','Trịnh Mạnh Hùng','ncc','Cá nhân',5,0,true),
  ('CTY072','Công ty TNHH Thương mại và Dịch vụ Nam Trường Khang','ncc','Công ty',5,0,true),
  ('CN073','TRƯƠNG THỊ KIM PHƯỢNG','ncc','Cá nhân',5,0,true),
  ('CN074','Phạm Công Duy- phòng Marketing TNEC','ncc','Cá nhân (nội bộ)',5,0,true),
  ('CTY075','Công ty cổ phần vật liệu xây dựng Mansa Vina','ncc','Công ty',4,0,true),
  ('CTY076','Doanh nghiệp tư nhân Lê Văn Minh','ncc','Công ty',4,0,true),
  ('CTY077','CÔNG TY TRÁCH NHIỆM HỮU HẠN HỮU BIÊN','ncc','Công ty',4,0,true),
  ('CTY078','Công Ty TNHH Xây Dựng Trang Trí Nội Thất C.A.S VN','ncc','Công ty',4,0,true),
  ('CTY079','Công ty TNHH Xây dựng Phát triển Hạ tầng Trung Quân','ncc','Công ty',4,0,true),
  ('CTY080','Công ty TNHH Tư Vấn Thiết Kế Phần Mềm Cánh Cam','ncc','Công ty',4,0,true),
  ('CN081','TRUNG TÂM ĐIỆN MÁY ĐIỆN LẠNH HIỆP PHÁT - LÊ THỊ BÌNH TRỊ','ncc','Cá nhân',4,0,true),
  ('CN082','CHU ĐÌNH CHÍ','ncc','Cá nhân',4,0,true),
  ('CTY083','CÔNG TY TNHH ĐIỆN MÁY AN VY','ncc','Công ty',4,0,true),
  ('CTY084','Công ty TNHH Đầu Tư TM DV Thành Hưng Việt Nam','ncc','Công ty',4,0,true),
  ('CN085','Lê Thị Bích Trâm','ncc','Cá nhân',4,0,true),
  ('CTY086','Công ty TNHH Thiết bị Văn phòng Khôi Nguyên','ncc','Công ty',4,0,true),
  ('CN087','Nguyễn Văn Bảy','ncc','Cá nhân',4,0,true),
  ('CTY088','Công ty CP Tập Đoàn Song Tạo','ncc','Công ty',4,0,true),
  ('CN089','Nguyễn Anh Dũng','ncc','Cá nhân',4,0,true),
  ('CN090','Đinh Đức Tâm','ncc','Cá nhân',4,0,true),
  ('NH091','Ngân Hàng TMCP Tiên Phong - Chi nhánh Cửu Long','ncc','Ngân hàng',4,0,true),
  ('CTY092','Công ty Cổ phần Thủy Điện Trung Nam','ncc','Công ty',4,0,true),
  ('CTY093','Công ty TNHH MTV Xây Dựng Thành Hân','ncc','Công ty',3,0,true),
  ('CN094','PHẠM ĐỨC KIÊN','ncc','Cá nhân',3,0,true),
  ('CTY095','CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ VÀ CÔNG NGHỆ HOÀNG LONG','ncc','Công ty',3,0,true),
  ('CTY096','Công ty TNHH Thương mại Laria','ncc','Công ty',3,0,true),
  ('CTY097','Công ty TNHH Cao Phong','ncc','Công ty',3,0,true),
  ('CTY098','Công ty TNHH Đầu tư và Phát triển Hệ thống Đấu Thầu qua Mạng Quốc Gia','ncc','Công ty',3,0,true),
  ('CTY099','Công ty TNHH I-TTP','ncc','Công ty',3,0,true),
  ('CTY100','Công ty TNHH Thương mại và Dịch vụ Kỹ thuật Diệu Phúc','ncc','Công ty',3,0,true),
  ('CTY101','CÔNG TY TNHH THƯƠNG MẠI ĐẦU TƯ VÀ XÂY LẮP ĐIỆN XANH','ncc','Công ty',3,0,true),
  ('CTY102','CÔNG TY CỔ PHẦN ĐẦU TƯ ĐIỆN MÁY XANH','ncc','Công ty',3,0,true),
  ('CTY103','Công ty TNHH TM Vận Tải Du Lịch SAIGONCARS','ncc','Công ty',3,0,true),
  ('CTY104','CÔNG TY TNHH PHÁT TRIỂN KHOA HỌC QUỐC TẾ TRƯỜNG SINH','ncc','Công ty',3,0,true),
  ('CN105','Phú Thành Hảo','ncc','Cá nhân',3,0,true),
  ('CTY106','Công ty TNHH In ấn Bao bì Nhật Duy','ncc','Công ty',3,0,true),
  ('CN107','Hồ Bá Hùng','ncc','Cá nhân',3,0,true),
  ('CQ108','BAN QUẢN LÝ DỰ ÁN TỈNH AN GIANG','ncc','Cơ quan NN',3,0,true),
  ('CTY109','Công ty TNHH Thép Thế Hưng','ncc','Công ty',3,0,true),
  ('CTY110','Công ty CP Bê tông Xanh Đà Nẵng','ncc','Công ty',3,0,true),
  ('CTY111','Công ty TNHH TM và DV Mạnh Thành Hưng','ncc','Công ty',3,0,true),
  ('CTY112','Công ty TNHH xây dựng Phước Vạn Thịnh','ncc','Công ty',2,0,true),
  ('CTY113','Công ty Trách nhiệm Hữu hạn Thương mại và Xây dựng Dịch vụ Dương Đông','ncc','Công ty',2,0,true),
  ('CTY114','CÔNG TY TNHH ĐẦU TƯ XÂY DỰNG VÀ MÔI TRƯỜNG HUY HOÀNG','ncc','Công ty',2,0,true),
  ('CTY115','CÔNG TY TNHH ENVIRO WORLD','ncc','Công ty',2,0,true),
  ('CTY116','CÔNG TY TRÁCH NHIỆM HỮU HẠN AN LIM','ncc','Công ty',2,0,true),
  ('CTY117','Công ty TNHH Một thành viên Đô La Thành','ncc','Công ty',2,0,true),
  ('CTY118','CÔNG TY TNHH MTV ĐẠI THÀNH PHÁT','ncc','Công ty',2,0,true),
  ('CTY119','CÔNG TY TNHH THƯƠNG MẠI VÀ DỊCH VỤ GOAT','ncc','Công ty',2,0,true),
  ('CN120','TCT Bảo Hiểm PVI - Chi Nhánh Bảo Hiểm PVI Đồng Khởi','ncc','Cá nhân',2,0,true),
  ('CTY121','Tổng Công ty Cổ phần Bảo hiểm Petrolimex','ncc','Công ty',2,0,true),
  ('CTY122','Công ty TNHH Cơ khí Xây dựng Chấn Hưng Thịnh','ncc','Công ty',2,0,true),
  ('CTY123','CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI ZEEUNI','ncc','Công ty',2,0,true),
  ('CTY124','Công ty TNHH XD TM DV SX Phát Hưng Khang','ncc','Công ty',2,0,true),
  ('CTY125','CÔNG TY CỔ PHẦN CHỨNG NHẬN VÀ GIÁM ĐỊNH QUỐC TẾ ISOCERT','ncc','Công ty',2,0,true),
  ('CTY126','CÔNG TY TNHH VẬT TƯ XÂY DỰNG ĐỨC NHÂN','ncc','Công ty',2,0,true),
  ('CTY127','CÔNG TY TNHH VẬT LIỆU XÂY DỰNG THANH NGỌC BẠC LIÊU','ncc','Công ty',2,0,true),
  ('CN128','Chu Bảo Quốc','ncc','Cá nhân',2,0,true),
  ('CTY129','Công ty TNHH Một thành viên Thương mại Thúy Ngọc','ncc','Công ty',2,0,true),
  ('CN130','VŨ THỊ THU HÀ','ncc','Cá nhân',2,0,true),
  ('CTY131','Công ty Cổ phần Công nghệ và Tư vấn CIC','ncc','Công ty',2,0,true),
  ('CN132','Sở Tài chính tỉnh Đồng Tháp','ncc','Cá nhân',2,0,true),
  ('CTY133','CÔNG TY TNHH SẢN XUẤT NỘI THẤT TUYẾT HÀ','ncc','Công ty',2,0,true),
  ('CTY134','Công ty TNHH Một thành viên Viễn thông Quốc tế FPT','ncc','Công ty',2,0,true),
  ('CTY135','Công ty TNHH Sản xuất Thương mại NT Nguyễn Minh','ncc','Công ty',2,0,true),
  ('CTY136','Công ty TNHH Nội Thất Nam Việt DECOR','ncc','Công ty',2,0,true),
  ('CN137','Hộ Kinh Doanh Diệp Mỹ Hà','ncc','Cá nhân',2,0,true),
  ('CTY138','CÔNG TY TNHH CƠ KHÍ VÀ XÂY DỰNG PHAN HẢI','ncc','Công ty',2,0,true),
  ('CTY139','Công ty Cổ phần Thương mại - Dịch vụ Phong Vũ','ncc','Công ty',2,0,true),
  ('CTY140','Công ty TNHH Thương mại Dịch vụ Vận tải Trung Thuận','ncc','Công ty',2,0,true),
  ('CTY141','Công ty Cổ phần Phần mềm Viễn Thông Miền Nam','ncc','Công ty',2,0,true),
  ('CTY142','Chi nhánh Nam Trung Bộ - Công ty Cổ phần Xây dựng và Lắp Máy Trung Nam','ncc','Công ty',2,0,true),
  ('CTY143','Công ty TNHH Một thành viên Hòa Hiền','ncc','Công ty',2,0,true),
  ('CTY144','CÔNG TY TNHH AROMA SB','ncc','Công ty',2,0,true),
  ('CTY145','Công ty Bảo hiểm MIC Bến Thành','ncc','Công ty',2,0,true),
  ('CTY146','Công ty CP Tuyên Truyền Và Phát Triển Thông Tin Kinh Tế Hội Nhập','ncc','Công ty',2,0,true),
  ('CTY147','CÔNG TY TNHH THƯƠNG MẠI NỘI THẤT MỘC VIỆT','ncc','Công ty',2,0,true),
  ('CTY148','Công ty TNHH Trang trí Nội thất Phim Cách nhiệt Phương Nam','ncc','Công ty',2,0,true),
  ('CTY149','Công ty TNHH Quảng cáo Đức An','ncc','Công ty',2,0,true),
  ('CTY150','Trung tâm Kinh doanh VNPT - Tp HCM - Chi nhánh Tổng Công ty Dịch vụ Viễn thông','ncc','Công ty',2,0,true),
  ('CN151','Trần Hồng Quân','ncc','Cá nhân',2,0,true),
  ('CN152','Trung Tâm Quản Lý Mạng Lưới Trạm Định Vị Vệ Tinh Quốc Gia','ncc','Cá nhân',2,0,true),
  ('CTY153','Công Ty TNHH Môi Trường Cao Gia Quý','ncc','Công ty',2,0,true),
  ('CTY154','Công Ty TNHH Huấn Luyện Dịch Vụ Kỹ Thuật Việt Nam','ncc','Công ty',2,0,true),
  ('CTY155','Công ty TNHH Thiết bị Giải pháp Công nghệ Duy Anh','ncc','Công ty',2,0,true),
  ('CN156','Nguyễn Đức Hùng','ncc','Cá nhân',2,0,true),
  ('CN157','Nguyễn Anh Khoa','ncc','Cá nhân',2,0,true),
  ('CTY158','CÔNG TY TNHH DV DƯƠNG PHÚC VN','ncc','Công ty',2,0,true),
  ('CTY159','CÔNG TY CỔ PHẦN THƯƠNG MẠI VIỆT CLEAN','ncc','Công ty',2,0,true),
  ('CTY160','Công ty TNHH In và Quảng cáo Phước Chi','ncc','Công ty',2,0,true),
  ('CN161','Lê Minh Tiến','ncc','Cá nhân',2,0,true),
  ('CTY162','CÔNG TY TNHH TRANG TRÍ NỘI NGOẠI THẤT VIỆT HOME','ncc','Công ty',2,0,true),
  ('CTY163','CÔNG TY TNHH TM DV SỰ KIỆN EVENTWORLD','ncc','Công ty',2,0,true),
  ('CTY164','Công ty Cổ phần Tư vấn An toàn và Môi trường Sài Gòn','ncc','Công ty',2,0,true),
  ('CTY165','Công ty TNHH Thương mại Dịch vụ V&A','ncc','Công ty',2,0,true),
  ('CTY166','CÔNG TY TNHH MIKASPORT','ncc','Công ty',2,0,true),
  ('CTY167','Công ty TNHH TM DV Truyền Thông BITE','ncc','Công ty',2,0,true),
  ('CTY168','Công ty Cổ Phần JUST VIET','ncc','Công ty',2,0,true),
  ('CTY169','Công ty TNHH Cung Cấp Phần Mềm Chữ Ký Số Việt Nam','ncc','Công ty',2,0,true),
  ('CTY170','Trung tâm Kinh doanh VNPT - Bắc Ninh - Chi nhánh Tổng Công ty Dịch vụ Viễn thông','ncc','Công ty',2,0,true),
  ('CTY171','CÔNG TY TNHH THIẾT KẾ - IN ẤN MINH KHANG','ncc','Công ty',2,0,true),
  ('CN172','Lê Trần Trung Hiếu','ncc','Cá nhân',2,0,true),
  ('CTY173','Công ty Cổ phần Ánh Dương Việt Nam','ncc','Công ty',2,0,true),
  ('CTY174','CÔNG TY CỔ PHẦN QUẢN LÝ VÀ VẬN HÀNH CAO ỐC KHÁNH HỘI','ncc','Công ty',2,0,true),
  ('CQ175','Ban Quản lý Dự án Đầu tư Xây dựng tỉnh Đồng Nai','ncc','Cơ quan NN',2,0,true),
  ('CTY176','Công ty Cổ phần Điện Mặt Trời Trung Nam Trà Vinh','ncc','Công ty',2,0,true),
  ('CN177','Phạm Thanh Yy-KHDA','ncc','Cá nhân',2,0,true),
  ('CTY178','Công ty TNHH đầu tư TM Sarina','ncc','Công ty',2,0,true),
  ('CTY179','Công ty TNHH TM và DV CNS','ncc','Công ty',2,0,true),
  ('CTY180','CTY CP XD VA LAP MAY TRUNG NAM','ncc','Công ty',2,0,true),
  ('CTY181','Công ty TNHH Thiết kế Xây dựng FuTu','ncc','Công ty',2,0,true),
  ('CN182','CNE&C - MT','ncc','Cá nhân',2,0,true),
  ('CN183','Huy Hoàng','ncc','Cá nhân',2,0,true),
  ('CTY184','Cty SMC','ncc','Công ty',2,0,true),
  ('CN185','THANH PHONG','ncc','Cá nhân',2,0,true),
  ('CTY186','Công ty TNHH Đầu tư và xây dựng HPT','ncc','Công ty',1,0,true),
  ('CTY187','Công ty Cổ phần Kỹ thuật & Xây dựng Công Minh','ncc','Công ty',1,0,true),
  ('CTY188','Công ty Trách Nhiệm Hữu Hạn Nga Hải','ncc','Công ty',1,0,true),
  ('CTY189','Công ty Cổ phần Tiếp Vận Và Xây Lắp Hải Vương 68','ncc','Công ty',1,0,true),
  ('CTY190','CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI DỊCH VỤ ĐẦU TƯ XÂY DỰNG ST 16','ncc','Công ty',1,0,true),
  ('CTY191','Công ty Cổ phần Thương mại Dịch vụ Phan Phước','ncc','Công ty',1,0,true),
  ('CTY192','CÔNG TY CỔ PHẦN XÂY DỰNG HOA SEN','ncc','Công ty',1,0,true),
  ('CQ193','Cục Thuế Lâm Đồng','ncc','Cơ quan NN',1,0,true),
  ('CTY194','CÔNG TY TNHH XÂY DỰNG VẬN TẢI THƯƠNG MẠI CHÍ PHÚC','ncc','Công ty',1,0,true),
  ('CN195','Thuế vãng lai tỉnh Vĩnh Long','ncc','Cá nhân',1,0,true),
  ('CTY196','CÔNG TY TNHH ĐẦU TƯ SẢN XUẤT THƯƠNG MẠI BÊ TÔNG PHÚ HƯNG BẠC LIÊU','ncc','Công ty',1,0,true),
  ('CTY197','Công ty Cổ Phần Thương Mại Dịch Vụ CC1','ncc','Công ty',1,0,true),
  ('CTY198','Công ty TNHH Tư vấn Thiết Kế Thắng Lợi','ncc','Công ty',1,0,true),
  ('CTY199','Công ty TNHH Công Nghệ Kỹ Thuật Điện An Nguyễn','ncc','Công ty',1,0,true),
  ('CTY200','CÔNG TY CP TƯ VẤN KIỂM ĐỊNH CÀ MAU','ncc','Công ty',1,0,true),
  ('CTY201','Công Ty Cổ Phần Thương Mại Đầu Tư Phát Triển DO Holdings','ncc','Công ty',1,0,true),
  ('CTY202','CÔNG TY CỔ PHẦN TƯ VẤN XÂY DỰNG VÀ THƯƠNG MẠI PHƯƠNG QUÂN','ncc','Công ty',1,0,true),
  ('CTY203','Công ty Cổ phần Thương mại và Dịch vụ Công nghệ số Đỉnh Cao','ncc','Công ty',1,0,true),
  ('CTY204','CÔNG TY TNHH HA FOOD VN','ncc','Công ty',1,0,true),
  ('CTY205','Công ty TNHH Đại Cát Bình Minh','ncc','Công ty',1,0,true),
  ('CTY206','Công ty Trách nhiệm Hữu hạn PACE','ncc','Công ty',1,0,true),
  ('CTY207','CÔNG TY TNHH CUNG ỨNG VẬT TƯ XĂNG DẦU HÓA CHẤT PETROCHEM','ncc','Công ty',1,0,true),
  ('CTY208','Công ty Cổ phần Tư vấn Nền móng và Xây dựng Tekco','ncc','Công ty',1,0,true),
  ('CTY209','Công ty Cổ phần Quảng cáo Thương mại Sen Vàng','ncc','Công ty',1,0,true),
  ('CTY210','Công Ty TNHH SX TM DV Bạt Nhựa Hàn Việt','ncc','Công ty',1,0,true),
  ('CTY211','CÔNG TY CỔ PHẦN VIRTUAL DESIRE EVENTS','ncc','Công ty',1,0,true),
  ('CTY212','Công Ty TNHH Thương Mại Dịch Vụ Tú Tú Uyên','ncc','Công ty',1,0,true),
  ('CTY213','CÔNG TY TNHH ME MEDIA','ncc','Công ty',1,0,true),
  ('CTY214','Công ty CP tư vấn đầu tư xây dựng An Hậu','ncc','Công ty',1,0,true),
  ('CN215','NGUYỄN VĂN KÍNH','ncc','Cá nhân',1,0,true),
  ('CN216','Nguyễn Vĩnh Thái-BĐH Dự án cầu vượt Tỉnh lộ 8','ncc','Cá nhân (nội bộ)',1,0,true),
  ('CN217','Nguyễn Văn Sơn','ncc','Cá nhân',1,0,true),
  ('CTY218','Công ty Cổ phần Hệ Sinh thái Đấu Thầu','ncc','Công ty',1,0,true),
  ('CTY219','CÔNG TY TNHH ĐẦU TƯ THƯƠNG MẠI DỊCH VỤ PHỐ 79','ncc','Công ty',1,0,true),
  ('CTY220','Công ty TNHH Thương mại và Du lịch Kiwi','ncc','Công ty',1,0,true),
  ('CTY221','Công ty TNHH Lê Gia Vinh','ncc','Công ty',1,0,true),
  ('CN222','TCT Bảo Hiểm PVI - Chi nhánh Bảo Hiểm PVI Tây Ninh','ncc','Cá nhân',1,0,true),
  ('CN223','Viện Chuyên nghành Cơ khí Tự động hóa Đo lường','ncc','Cá nhân',1,0,true),
  ('CTY224','Công Ty TNHH Một Thành Viên Sản Xuất Thương Mại Cơ Khí Nội Thất Thắng Phong','ncc','Công ty',1,0,true),
  ('CTY225','Công ty Cổ phần Xây dựng và Thương mại Gia Thịnh','ncc','Công ty',1,0,true),
  ('CTY226','Chi Nhánh Công ty TNHH Thương Mại - Dịch Vụ Vườn Cau','ncc','Công ty',1,0,true),
  ('CTY227','CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ NHÀ HÀNG KẦN KẨU','ncc','Công ty',1,0,true),
  ('CTY228','Công ty TNHH Ẩm Thực Trường An','ncc','Công ty',1,0,true),
  ('CTY229','Công ty TNHH Careerlink','ncc','Công ty',1,0,true),
  ('CTY230','Công ty TNHH TM DV Công Nghệ Hoàng Sơn','ncc','Công ty',1,0,true),
  ('CTY231','Công ty TNHH Duy Tín Travel','ncc','Công ty',1,0,true),
  ('CTY232','Công Ty TNHH TMDV Đầu Tư Xây Dựng TTC','ncc','Công ty',1,0,true),
  ('CTY233','CHI NHÁNH MIỀN TRUNG - CÔNG TY CP XÂY DỰNG VÀ LẮP MÁY TRUNG NAM','ncc','Công ty',1,0,true),
  ('CTY234','CÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI DỊCH VỤ NGUYÊN KHANG','ncc','Công ty',1,0,true),
  ('CTY235','Công Ty TNHH Thương Mại Nhà Thông Minh Homekit','ncc','Công ty',1,0,true),
  ('CTY236','Công ty Cổ phần Việc làm 24h','ncc','Công ty',1,0,true),
  ('CTY237','Công Ty TNHH Công Nghiệp Hòa Phát Sài Gòn','ncc','Công ty',1,0,true),
  ('CTY238','Công Ty TNHH Thương Mại Và Gia Công Đăng Phát','ncc','Công ty',1,0,true),
  ('CTY239','CHI NHÁNH TẠI THÀNH PHỐ HỒ CHÍ MINH - CÔNG TY CỔ PHẦN TOPCV VIỆT NAM','ncc','Công ty',1,0,true),
  ('CN240','Trường Đại học Kiến Trúc Thành phố Hồ Chí Minh','ncc','Cá nhân',1,0,true),
  ('CTY241','Công ty TNHH Dịch vụ Lộc Xanh','ncc','Công ty',1,0,true),
  ('CTY242','Công ty TNHH Quảng cáo Quốc Anh','ncc','Công ty',1,0,true),
  ('CTY243','Công ty TNHH Phần mềm FAST','ncc','Công ty',1,0,true),
  ('CTY244','CÔNG TY TNHH XUẤT NHẬP KHẨU THƯƠNG MẠI SONG VIỆT','ncc','Công ty',1,0,true),
  ('CTY245','Công Ty TNHH Trường Mai Sài Gòn','ncc','Công ty',1,0,true),
  ('CTY246','Công ty TNHH Thiết bị Công nghiệp Hưng Thịnh','ncc','Công ty',1,0,true),
  ('CTY247','CÔNG TY TNHH ĐẦU TƯ THƯƠNG MẠI SARINA','ncc','Công ty',1,0,true),
  ('CTY248','Công ty TNHH TM DV Vận Tải Khải Đăng','ncc','Công ty',1,0,true),
  ('CTY249','Công ty TNHH TM DV Hải Sơn Vi Na','ncc','Công ty',1,0,true),
  ('CTY250','Công ty Cổ phần Đầu tư Thương mại Dịch vụ Sài Gòn Ô tô Cần Thơ','ncc','Công ty',1,0,true),
  ('CTY251','Công ty Cổ Phần Môi Trường Xanh VN','ncc','Công ty',1,0,true),
  ('CTY252','Công ty TNHH Thương mại Điện tử Thành Đạt','ncc','Công ty',1,0,true),
  ('CTY253','CÔNG TY TNHH PHÁT TRIỂN SÀI GÒN ATN','ncc','Công ty',1,0,true),
  ('CN254','Trương Bảo Quốc','ncc','Cá nhân',1,0,true),
  ('CTY255','Công ty Bảo hiểm PVI Thành Đô','ncc','Công ty',1,0,true),
  ('CTY256','Công ty cổ phần Giáo dục PFL','ncc','Công ty',1,0,true),
  ('CN257','Trần Mạnh Hồ','ncc','Cá nhân',1,0,true),
  ('CN258','Đoàn Quang Mạnh','ncc','Cá nhân',1,0,true),
  ('CTY259','Công ty TNHH Sáu Hương','ncc','Công ty',1,0,true),
  ('CN260','Võ Thị Thanh Nhàn-phòng MKT TNE&C','ncc','Cá nhân (nội bộ)',1,0,true),
  ('CTY261','CÔNG TY TNHH BẢO HỘ XANH','ncc','Công ty',1,0,true),
  ('CTY262','Công ty TNHH Du lịch Sự kiện Quốc Tế MGM','ncc','Công ty',1,0,true),
  ('CTY263','Công ty TNHH Thương Mại Và Dịch Vụ HALLEY','ncc','Công ty',1,0,true),
  ('CTY264','CÔNG TY TNHH VOKS GROUP','ncc','Công ty',1,0,true),
  ('CN265','Lưu Thúy An-HCNS','ncc','Cá nhân (nội bộ)',1,0,true),
  ('CN266','Nguyễn Quốc Sứ','ncc','Cá nhân',1,0,true),
  ('CTY267','Công ty TNHH Thương mại Dịch vụ OSG','ncc','Công ty',1,0,true),
  ('CN268','Nguyễn Thị Hồng Hạnh','ncc','Cá nhân',1,0,true),
  ('CN269','Trung tâm Đấu thầu Qua Mạng Quốc Gia','ncc','Cá nhân',1,0,true),
  ('CQ270','Ban Quản lý Dự án đầu tư xây dựng hạ tầng đô thị Thành phố Hồ Chí Minh','ncc','Cơ quan NN',1,0,true),
  ('CQ271','Ban Quản lý Dự án Đầu tư Xây dựng các Công trình Giao thông','ncc','Cơ quan NN',1,0,true),
  ('CQ272','Ban quản lý Khu kinh tế tỉnh Đồng Tháp','ncc','Cơ quan NN',1,0,true),
  ('CTY273','CÔNG TY CỔ PHẦN - TỔNG CÔNG TY LỌC HÓA DẦU VIỆT NAM','ncc','Công ty',1,0,true),
  ('CQ274','Ban Quản lý Dự án Đầu tư và Xây dựng Thủy lợi 10','ncc','Cơ quan NN',1,0,true),
  ('CN275','Nguyễn Thị Thái Dương','ncc','Cá nhân',1,0,true),
  ('CN276','Lê Thiện Thanh','ncc','Cá nhân',1,0,true),
  ('CTY277','Công ty TNHH quảng cáo và xây dựng Đại Cát','ncc','Công ty',1,0,true),
  ('CN278','Nguyễn Ngọc Thanh Hằng-HCNS','ncc','Cá nhân (nội bộ)',1,0,true),
  ('CTY279','Công ty TNHH TM và gia công Đăng Phát','ncc','Công ty',1,0,true),
  ('CTY280','Công ty CP di chuyển xanh và thông minh GSM','ncc','Công ty',1,0,true),
  ('CTY281','Công ty CP TM xây dựng HPK','ncc','Công ty',1,0,true),
  ('CTY282','Công tyTNHH TM DV nước uống Lê Trần','ncc','Công ty',1,0,true),
  ('CTY283','Công ty TNHH TM và du lịch Kiwi','ncc','Công ty',1,0,true),
  ('CTY284','Công ty CP Virtual Desire Event','ncc','Công ty',1,0,true),
  ('CN285','Nguyễn Bích Như Quỳnh-HCNS','ncc','Cá nhân (nội bộ)',1,0,true),
  ('CTY286','Công ty CP Hai Bốn Bảy','ncc','Công ty',1,0,true),
  ('CTY287','Công ty CP đầu tư thịnh vượng HVC','ncc','Công ty',1,0,true),
  ('CTY288','Công ty CP TNHH SX TM DV Nguyên Khang','ncc','Công ty',1,0,true),
  ('CN289','Phạm Hoàng Đảo','ncc','Cá nhân',1,0,true),
  ('CN290','Hồ Hoàng Cường','ncc','Cá nhân',1,0,true),
  ('CTY291','Công ty CP VLXD Mansa Vina','ncc','Công ty',1,0,true),
  ('CN292','PHAN THI AI LOAN','ncc','Cá nhân',1,0,true),
  ('CTY293','CÔNG TY CP THỦY ĐIỆN TRUNG NAM','ncc','Công ty',1,0,true),
  ('CTY294','Công ty TNHH Giải pháp MT Đại Nam','ncc','Công ty',1,0,true),
  ('CTY295','Công ty TNHH XD Trang trí nội thất C.A.S VN','ncc','Công ty',1,0,true),
  ('CTY296','Công Ty TNHH DV An Ninh Bảo Vệ Long Thiên Bảo','ncc','Công ty',1,0,true),
  ('CTY297','Công ty TNHH Tư vấn Xây dựng Miền Đông','ncc','Công ty',1,0,true),
  ('CTY298','Công ty TNHH XD PTHT Trung Quân','ncc','Công ty',1,0,true),
  ('CTY299','Công ty TNHH XD Thuận Đức II','ncc','Công ty',1,0,true),
  ('CTY300','Công ty TNHH XD và TM Nhật Minh EC','ncc','Công ty',1,0,true),
  ('CTY301','Công ty TNHH MTV Hùng Bá','ncc','Công ty',1,0,true),
  ('CTY302','Công ty Thái Hưng Thịnh','ncc','Công ty',1,0,true),
  ('CTY303','Công ty TNHH Tuấn Thành Tiến','ncc','Công ty',1,0,true),
  ('CTY304','Công ty Cổ phần Sông Hàn INVEST','ncc','Công ty',1,0,true),
  ('CTY305','Công ty TNHH XD Trường Bản','ncc','Công ty',1,0,true),
  ('CTY306','Liên danh Công ty TNHH Tư vấn Khảo sát Xây dựng Toàn Chính và Công ty CP Đầu tư Xây dựng Thịnh Tín','ncc','Công ty',1,0,true),
  ('CTY307','Công ty Phúc Thành Phát','ncc','Công ty',1,0,true),
  ('CTY308','Công ty TNHH TM Xi Măng Tốt','ncc','Công ty',1,0,true),
  ('CTY309','Công Ty TNHH MTV Hòa Liên Hùng','ncc','Công ty',1,0,true),
  ('CTY310','Công Ty TNHH Tư vấn & Kiến tạo Cảnh quan VIETPARK','ncc','Công ty',1,0,true),
  ('CTY311','Công ty Phước Thịnh Phát','ncc','Công ty',1,0,true),
  ('CTY312','Công ty Quảng Cường','ncc','Công ty',1,0,true),
  ('CTY313','Công ty TNHH MTV Toàn Minh Thắng','ncc','Công ty',1,0,true),
  ('CTY314','Công ty CP Tập đoàn Cơ khí Cao su Trường Sơn','ncc','Công ty',1,0,true),
  ('CTY315','Công ty Cổ phần môi trường đô thị Đà Nẵng','ncc','Công ty',1,0,true),
  ('CTY316','Công ty Lộc Phước','ncc','Công ty',1,0,true),
  ('CTY317','Công ty TNHH Xây dựng Phát An Huy','ncc','Công ty',1,0,true),
  ('CTY318','Công ty SMC','ncc','Công ty',1,0,true),
  ('CN319','Hà Khánh','ncc','Cá nhân',1,0,true),
  ('CN320','Phú Hưng Bạc Liêu','ncc','Cá nhân',1,0,true),
  ('CN321','CC1','ncc','Cá nhân',1,0,true),
  ('CTY322','CTY NHIÊN THÔNG','ncc','Công ty',1,0,true),
  ('CTY323','CT TNHH HỮU BIÊN','ncc','Công ty',1,0,true),
  ('CTY324','CTY CP DV VÀ KT SMC','ncc','Công ty',1,0,true);